### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by RandomAltThing** [StickyPiston/StickyPiston#1]
@DefinitlyEvil @TheMCPEGamer @Nizarmah99 @Creeperface03 @MyNameIsAnti @CheesyFriedBacon @zhuowei @KsyMC @Byteandahalf @Minecraftdominator @Odin119 @MrAndyPE @DragonetMC @RedstoneLamp @PhilipShilling @PEMapModder @Pocketmine @BlockServerProject @Synchunk @Shoghicp @Dinnerbone @mojang @1x3y5 @Connor4898 @LegendOfMCPE @Atomictissue 

This is where I will be creating an MCPE Server Software with Mod support. It will be like <b>Bukkit</b> with server mod support. You will also be able to code plugins in Java, making it easier for developers to make them.

The software will also include:

- Plugins coded in Java
- Special API for Java mods for server 
- Possible ModPE support if @zhuowei updated BL source
- More cool stuff

If you would like to contribute in any way, or just keep an eye on the development, feel free to make pull request and I may add people to the organisation.

**Comment by RandomAltThing** [comment]
@peacestorm @kingbudderjr ^^

**Comment by Synchunk** [comment]
Do you always spam random people with emails when you create a new project?

**Comment by RandomAltThing** [comment]
Nope

**Comment by RandomAltThing** [comment]
No one can comment on this :)
