### ISSUE TITLE
Nice code theft - Reporting Org

### ISSUE THREAD

**Issue by PhilipShilling** [StickyPiston/StickyPiston#2]
I can see you stole code and ideas from my project. IE: Logger.java this org is being reported to the GitHub staff

**Comment by RandomAltThing** [comment]
I didnt steal anything. Look at 

BlockServerProject

Bukkitand many more.

**Comment by RandomAltThing** [comment]
I will be reporting RedstoneLamp, aswell.

**Comment by RandomAltThing** [comment]
@PhilipShilling Apparently there is not an option to report someone for "code theft". Only security issues and abuse.

**Comment by PhilipShilling** [comment]
Then why is it that your logger: https://github.com/StickyPiston/StickyPiston/blob/master/src/main/java/org/stickypiston/logger/Logger.java

Look incredibly similar to the Logger in my software? 
The answer: Stolen. I wasn't born yesterday. This violates the GNU GPL as it does not state that it uses code from the software you used the code. Also due to the fact that servers use command line input/output it would need to show the same notice. Please read the GNU GPL v3 and others. Main section of the GNU GPL: Secion 3.A. This is not the only section.

And yes there is. You also can not report our software as it, for one, existed before you, and two, follows any guidelines it needs to. Pick your battles and do your research.

**Comment by PhilipShilling** [comment]
Not only that but not long after you are banned from my org, this appears with the same code as mine as stated above.

**Comment by RandomAltThing** [comment]
So if I add a disclaimer with credit to you, your org, and your license then you won't keep complaining?

**Comment by PhilipShilling** [comment]
Are you kidding me? You are literally copy-pasting my code at this point.  All of your recent commits are obviously from my project.  Filing a DMCA Takedown.  You will be contacted by GitHub staff as to how to avoid this takedown as specified by me in my takedown.

**Comment by RandomAltThing** [comment]
What is up with you? Your time of the month I'm guessing?

**Comment by RandomAltThing** [comment]
@PhilipShilling Recent commits? I have edited Server.Java and StickyPiston.Java recently. They look completely different to yours. Please don't waste my time, I am going to block you.
